/*
introduction to Node.js

 Node.js
 Javascript Runtime environment
 used in server side programming
 Node REPL => Read Evaluate print loop

process : {object} -> provides information about, and control over the current node.js process.
process.argv : return arr containing command line argunments.

module.exports : a special object used to export to file of same directory.
require : function to include external modules that exist in diff files.

*/ 